
---
- name: Ensure file exists and display its contents on Windows
  hosts: windows
  tasks:
    - name: Check if file exists
      win_stat:
        path: C:\path\to\your\file.txt
      register: file_stat

    - name: Create file if it does not exist
      win_file:
        path: C:\path\to\your\file.txt
        state: touch
      when: not file_stat.stat.exists

    - name: Write content to the file
      win_lineinfile:
        path: C:\path\to\your\file.txt
        line: "This is the content of the file"
        create: yes

    - name: Display the content of the file
      win_shell: Get-Content C:\path\to\your\file.txt
      register: file_content

    - name: Show file content
      debug:
        msg: "{{ file_content.stdout_lines }}"
